version: "3.3"

services:
  db:
    container_name: tornado_db
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"


  server:
    build: .
    volumes:
      - .:/server
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - "db:database"

volumes:
  server: